### ISSUE TITLE
Appending Python Path

### ISSUE THREAD

**Issue by esplinj** [qcr/services#2]
Finding external Python packages requires python path to be appended within the "command" call for a given package inside service-config.yaml.

Current workaround based off Das' previous implementation when using qcr-env.bash bringup method..

Within /etc/qcr/qcr-env.bash, add the following line:
     export PYTHONPATH=/home/qcr/.local/lib/python3.8/site-packages:$PYTHONPATH

Then, sourcing the above bash script when running/launching the applicable node within service-config.yaml:
     command: source /etc/qcr/qcr-env.bash && rosrun usb4000 spectra.py

**Comment by jmount1992** [comment]
Proposed Solution:

At the top of a service configuration file have the following:

```yaml
append_to_pythonpath: <desired_path>
```

Then when creating the systemd service files the value of the `command` key is concatanated with the value of the proposed `append_to_pythonpath` key. Hence the ExecStart part of the systemd file would become:

```bash
ExecStart=/bin/bash -c "export PYTHONPATH=<value of append_to_pythonpath key>:$PYTHONPATH && <value of command key>"
```

Does that work?
